# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

          
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.7.0
      - uses: actions/checkout@v1
      - name: build
        run: cl /EHsc main.cpp /link /out:Prime.exe
        
      - name: art
        uses: actions/upload-artifact@v2
        with:
          name: my_art
          path: "*.exe"
          
      - name: Telegram
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: oops
